services:
  mongo:
    image: mongo:6
    container_name: helpdesk_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: ./server
    container_name: helpdesk_api
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: helpdesk_client
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  mongo_data:
